In [1]:
# ================================================================
# COMPLETE GOOGLE COLAB ANALYSIS
# ================================================================

import pandas as pd
import numpy as np
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")


# ================================================================
# 1. LOAD CLEANED DATASET
# ================================================================

file_path = "/content/cleaned_sample_dataset.xlsx"

df = pd.read_excel(file_path)

print("=" * 70)
print("TASK 14 - FAIRNESS & BIAS ANALYSIS")
print("=" * 70)

print("\nDataset loaded successfully.")

print("Rows    :", df.shape[0])
print("Columns :", df.shape[1])

print("\nColumns:")
print(df.columns.tolist())


# ================================================================
# 2. BASIC DATA OVERVIEW
# ================================================================

print("\n" + "=" * 70)
print("1. BASIC DATA OVERVIEW")
print("=" * 70)

print("\nDataset Shape:")
print(df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nFirst 5 Records:")
display(df.head())

print("\nStatistical Summary:")
display(df.describe(include="all").T)


# ================================================================
# 3. DATA QUALITY VALIDATION
# ================================================================

print("\n" + "=" * 70)
print("2. DATA QUALITY VALIDATION")
print("=" * 70)

print("\nMissing Values:")
missing_report = pd.DataFrame({
    "Missing_Values": df.isnull().sum(),
    "Missing_Percentage":
        (df.isnull().sum() / len(df) * 100).round(2)
})

display(missing_report)

print("\nDuplicate Records:")
print(df.duplicated().sum())


# ================================================================
# 4. IDENTIFY OUTCOME VARIABLE
# ================================================================

print("\n" + "=" * 70)
print("3. OUTCOME VARIABLE")
print("=" * 70)

outcome_column = "decision"

print("Outcome Variable:", outcome_column)

print("\nOutcome Distribution:")
outcome_distribution = df[outcome_column].value_counts()

display(outcome_distribution.to_frame("Count"))

print("\nOutcome Percentage:")
outcome_percentage = (
    df[outcome_column]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .to_frame("Percentage")
)

display(outcome_percentage)


# ================================================================
# 5. CREATE BINARY OUTCOME
# ================================================================

df["approved_flag"] = (
    df["decision"]
    .str.lower()
    .eq("approved")
    .astype(int)
)

print("\nApproved = 1")
print("Rejected = 0")

print("\nOverall Approval Rate:",
      round(df["approved_flag"].mean() * 100, 2), "%")


# ================================================================
# 6. GROUP DISTRIBUTION
# ================================================================

print("\n" + "=" * 70)
print("4. GROUP DISTRIBUTION")
print("=" * 70)

group_columns = [
    "gender",
    "region",
    "education"
]

for col in group_columns:

    print("\n---", col.upper(), "---")

    group_count = (
        df[col]
        .value_counts(dropna=False)
        .to_frame("Count")
    )

    group_count["Percentage"] = (
        group_count["Count"] /
        len(df) * 100
    ).round(2)

    display(group_count)


# ================================================================
# 7. OUTCOME DISPARITY BY GENDER
# ================================================================

print("\n" + "=" * 70)
print("5. OUTCOME DISPARITY - GENDER")
print("=" * 70)

gender_analysis = (
    df.groupby("gender")
    .agg(
        Total_Applications=("approved_flag", "size"),
        Approved=("approved_flag", "sum"),
        Approval_Rate=("approved_flag", "mean")
    )
    .reset_index()
)

gender_analysis["Approval_Rate"] = (
    gender_analysis["Approval_Rate"] * 100
).round(2)

gender_analysis["Rejection_Rate"] = (
    100 - gender_analysis["Approval_Rate"]
).round(2)

display(gender_analysis)


# ================================================================
# 8. OUTCOME DISPARITY BY REGION
# ================================================================

print("\n" + "=" * 70)
print("6. OUTCOME DISPARITY - REGION")
print("=" * 70)

region_analysis = (
    df.groupby("region")
    .agg(
        Total_Applications=("approved_flag", "size"),
        Approved=("approved_flag", "sum"),
        Approval_Rate=("approved_flag", "mean")
    )
    .reset_index()
)

region_analysis["Approval_Rate"] = (
    region_analysis["Approval_Rate"] * 100
).round(2)

region_analysis["Rejection_Rate"] = (
    100 - region_analysis["Approval_Rate"]
).round(2)

display(region_analysis)


# ================================================================
# 9. OUTCOME DISPARITY BY EDUCATION
# ================================================================

print("\n" + "=" * 70)
print("7. OUTCOME DISPARITY - EDUCATION")
print("=" * 70)

education_analysis = (
    df.groupby("education")
    .agg(
        Total_Applications=("approved_flag", "size"),
        Approved=("approved_flag", "sum"),
        Approval_Rate=("approved_flag", "mean")
    )
    .reset_index()
)

education_analysis["Approval_Rate"] = (
    education_analysis["Approval_Rate"] * 100
).round(2)

education_analysis["Rejection_Rate"] = (
    100 - education_analysis["Approval_Rate"]
).round(2)

display(education_analysis)


# ================================================================
# 10. DISPARITY CALCULATION FUNCTION
# ================================================================

def calculate_disparity(data, group_column):

    result = (
        data.groupby(group_column)["approved_flag"]
        .agg(["count", "sum", "mean"])
        .reset_index()
    )

    result.columns = [
        group_column,
        "Applications",
        "Approved",
        "Approval_Rate"
    ]

    result["Approval_Rate"] = (
        result["Approval_Rate"] * 100
    ).round(2)

    highest_rate = result["Approval_Rate"].max()
    lowest_rate = result["Approval_Rate"].min()

    result["Approval_Rate_Difference_From_Highest"] = (
        highest_rate - result["Approval_Rate"]
    ).round(2)

    if highest_rate != 0:
        result["Selection_Rate_Ratio"] = (
            result["Approval_Rate"] /
            highest_rate
        ).round(3)
    else:
        result["Selection_Rate_Ratio"] = np.nan

    return result


# ================================================================
# 11. GENDER DISPARITY METRICS
# ================================================================

print("\n" + "=" * 70)
print("8. GENDER DISPARITY METRICS")
print("=" * 70)

gender_disparity = calculate_disparity(
    df,
    "gender"
)

display(gender_disparity)


# ================================================================
# 12. REGION DISPARITY METRICS
# ================================================================

print("\n" + "=" * 70)
print("9. REGION DISPARITY METRICS")
print("=" * 70)

region_disparity = calculate_disparity(
    df,
    "region"
)

display(region_disparity)


# ================================================================
# 13. EDUCATION DISPARITY METRICS
# ================================================================

print("\n" + "=" * 70)
print("10. EDUCATION DISPARITY METRICS")
print("=" * 70)

education_disparity = calculate_disparity(
    df,
    "education"
)

display(education_disparity)


# ================================================================
# 14. IDENTIFY HIGHEST & LOWEST APPROVAL GROUPS
# ================================================================

print("\n" + "=" * 70)
print("11. HIGHEST & LOWEST APPROVAL GROUPS")
print("=" * 70)

def highest_lowest(result, group_column):

    highest = result.loc[
        result["Approval_Rate"].idxmax()
    ]

    lowest = result.loc[
        result["Approval_Rate"].idxmin()
    ]

    print("\nGroup:", group_column)

    print(
        "Highest Approval:",
        highest[group_column],
        "->",
        highest["Approval_Rate"],
        "%"
    )

    print(
        "Lowest Approval:",
        lowest[group_column],
        "->",
        lowest["Approval_Rate"],
        "%"
    )

    print(
        "Absolute Difference:",
        round(
            highest["Approval_Rate"] -
            lowest["Approval_Rate"],
            2
        ),
        "percentage points"
    )


highest_lowest(
    gender_disparity,
    "gender"
)

highest_lowest(
    region_disparity,
    "region"
)

highest_lowest(
    education_disparity,
    "education"
)


# ================================================================
# 15. FOUR-FIFTHS / 80% RULE SCREENING
# ================================================================

print("\n" + "=" * 70)
print("12. 80% RULE SCREENING")
print("=" * 70)

print("""
This is a screening indicator, not a final legal conclusion.

A selection-rate ratio below 0.80 can indicate a potential
disparity that requires further investigation.
""")

def eighty_percent_screen(result, group_column):

    result = result.copy()

    highest_rate = result["Approval_Rate"].max()

    result["Selection_Rate_Ratio"] = (
        result["Approval_Rate"] /
        highest_rate
    ).round(3)

    result["Potential_Disparity"] = np.where(
        result["Selection_Rate_Ratio"] < 0.80,
        "Review Required",
        "No Automatic Flag"
    )

    print("\n", group_column.upper())

    display(result)

    return result


gender_80 = eighty_percent_screen(
    gender_disparity,
    "gender"
)

region_80 = eighty_percent_screen(
    region_disparity,
    "region"
)

education_80 = eighty_percent_screen(
    education_disparity,
    "education"
)


# ================================================================
# 16. OUTCOME DISPARITY BY GENDER + REGION
# ================================================================

print("\n" + "=" * 70)
print("13. GENDER + REGION ANALYSIS")
print("=" * 70)

gender_region = (
    df.groupby(["gender", "region"])
    .agg(
        Applications=("approved_flag", "size"),
        Approved=("approved_flag", "sum"),
        Approval_Rate=("approved_flag", "mean")
    )
    .reset_index()
)

gender_region["Approval_Rate"] = (
    gender_region["Approval_Rate"] * 100
).round(2)

display(gender_region)


# ================================================================
# 17. GENDER + EDUCATION ANALYSIS
# ================================================================

print("\n" + "=" * 70)
print("14. GENDER + EDUCATION ANALYSIS")
print("=" * 70)

gender_education = (
    df.groupby(["gender", "education"])
    .agg(
        Applications=("approved_flag", "size"),
        Approved=("approved_flag", "sum"),
        Approval_Rate=("approved_flag", "mean")
    )
    .reset_index()
)

gender_education["Approval_Rate"] = (
    gender_education["Approval_Rate"] * 100
).round(2)

display(gender_education)


# ================================================================
# 18. INCOME ANALYSIS BY GROUP
# ================================================================

print("\n" + "=" * 70)
print("15. INCOME ANALYSIS BY GROUP")
print("=" * 70)

income_by_gender = (
    df.groupby("gender")["annual_income"]
    .agg(
        Average_Income="mean",
        Median_Income="median"
    )
    .round(2)
    .reset_index()
)

display(income_by_gender)


# ================================================================
# 19. CREDIT SCORE ANALYSIS BY GROUP
# ================================================================

print("\n" + "=" * 70)
print("16. CREDIT SCORE ANALYSIS BY GROUP")
print("=" * 70)

credit_by_gender = (
    df.groupby("gender")["credit_score"]
    .agg(
        Average_Credit_Score="mean",
        Median_Credit_Score="median"
    )
    .round(2)
    .reset_index()
)

display(credit_by_gender)


# ================================================================
# 20. APPROVAL RATE VS CREDIT SCORE
# ================================================================

print("\n" + "=" * 70)
print("17. CREDIT SCORE BAND ANALYSIS")
print("=" * 70)

df["credit_score_band"] = pd.cut(
    df["credit_score"],
    bins=[299, 579, 669, 739, 850],
    labels=[
        "Poor",
        "Fair",
        "Good",
        "Very Good"
    ]
)

credit_band_analysis = (
    df.groupby(
        "credit_score_band",
        observed=False
    )
    .agg(
        Applications=("approved_flag", "size"),
        Approved=("approved_flag", "sum"),
        Approval_Rate=("approved_flag", "mean")
    )
    .reset_index()
)

credit_band_analysis["Approval_Rate"] = (
    credit_band_analysis["Approval_Rate"] * 100
).round(2)

display(credit_band_analysis)


# ================================================================
# 21. APPROVAL RATE VS INCOME BAND
# ================================================================

print("\n" + "=" * 70)
print("18. INCOME BAND ANALYSIS")
print("=" * 70)

df["income_band"] = pd.cut(
    df["annual_income"],
    bins=[0, 40000, 70000, 100000, np.inf],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High"
    ]
)

income_band_analysis = (
    df.groupby(
        "income_band",
        observed=False
    )
    .agg(
        Applications=("approved_flag", "size"),
        Approved=("approved_flag", "sum"),
        Approval_Rate=("approved_flag", "mean")
    )
    .reset_index()
)

income_band_analysis["Approval_Rate"] = (
    income_band_analysis["Approval_Rate"] * 100
).round(2)

display(income_band_analysis)


# ================================================================
# 22. APPROVAL RATE VS AGE GROUP
# ================================================================

print("\n" + "=" * 70)
print("19. AGE BAND ANALYSIS")
print("=" * 70)

df["age_band"] = pd.cut(
    df["age"],
    bins=[17, 25, 35, 45, 55, 100],
    labels=[
        "18-25",
        "26-35",
        "36-45",
        "46-55",
        "56+"
    ]
)

age_analysis = (
    df.groupby(
        "age_band",
        observed=False
    )
    .agg(
        Applications=("approved_flag", "size"),
        Approved=("approved_flag", "sum"),
        Approval_Rate=("approved_flag", "mean")
    )
    .reset_index()
)

age_analysis["Approval_Rate"] = (
    age_analysis["Approval_Rate"] * 100
).round(2)

display(age_analysis)


# ================================================================
# 23. CONSENT ANALYSIS
# ================================================================

print("\n" + "=" * 70)
print("20. CONSENT ANALYSIS")
print("=" * 70)

consent_column = "consent_for_fairness_audit"

consent_analysis = (
    df.groupby(consent_column)
    .agg(
        Applications=("approved_flag", "size"),
        Approved=("approved_flag", "sum"),
        Approval_Rate=("approved_flag", "mean")
    )
    .reset_index()
)

consent_analysis["Approval_Rate"] = (
    consent_analysis["Approval_Rate"] * 100
).round(2)

display(consent_analysis)

print("\nConsent Distribution:")
display(
    df[consent_column]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .to_frame("Percentage")
)


# ================================================================
# 24. SAMPLE SIZE CHECK
# ================================================================

print("\n" + "=" * 70)
print("21. SAMPLE SIZE CHECK")
print("=" * 70)

for col in group_columns:

    print("\n", col.upper())

    sample_size = (
        df[col]
        .value_counts()
        .to_frame("Sample_Size")
    )

    sample_size["Small_Group_Flag"] = np.where(
        sample_size["Sample_Size"] < 30,
        "Small Sample - Interpret Carefully",
        "Adequate for Descriptive Analysis"
    )

    display(sample_size)


# ================================================================
# 25. OVERALL FAIRNESS SUMMARY
# ================================================================

print("\n" + "=" * 70)
print("22. OVERALL FAIRNESS SUMMARY")
print("=" * 70)

summary_rows = []

for name, result, group_column in [
    ("Gender", gender_disparity, "gender"),
    ("Region", region_disparity, "region"),
    ("Education", education_disparity, "education")
]:

    highest = result["Approval_Rate"].max()
    lowest = result["Approval_Rate"].min()

    summary_rows.append({
        "Group_Type": name,
        "Highest_Approval_Rate": highest,
        "Lowest_Approval_Rate": lowest,
        "Absolute_Disparity":
            round(highest - lowest, 2),
        "Lowest_to_Highest_Ratio":
            round(lowest / highest, 3)
            if highest != 0 else np.nan
    })

fairness_summary = pd.DataFrame(summary_rows)

display(fairness_summary)


# ================================================================
# 26. IDENTIFY AREAS REQUIRING REVIEW
# ================================================================

print("\n" + "=" * 70)
print("23. AREAS REQUIRING REVIEW")
print("=" * 70)

review_items = []

for _, row in fairness_summary.iterrows():

    if row["Lowest_to_Highest_Ratio"] < 0.80:

        review_items.append({
            "Group_Type": row["Group_Type"],
            "Issue":
                "Selection-rate ratio below 0.80",
            "Action":
                "Investigate potential outcome disparity"
        })

    else:

        review_items.append({
            "Group_Type": row["Group_Type"],
            "Issue":
                "No automatic 80% rule flag",
            "Action":
                "Continue monitoring"
        })

review_df = pd.DataFrame(review_items)

display(review_df)


# ================================================================
# 27. MONITORING BASELINE
# ================================================================

print("\n" + "=" * 70)
print("24. FAIRNESS MONITORING BASELINE")
print("=" * 70)

monitoring_baseline = fairness_summary.copy()

monitoring_baseline["Monitoring_Status"] = "Baseline Established"

display(monitoring_baseline)


# ================================================================
# 28. CREATE MONTHLY MONITORING DATA
# ================================================================

print("\n" + "=" * 70)
print("25. MONTHLY FAIRNESS MONITORING")
print("=" * 70)

df["application_month"] = (
    pd.to_datetime(df["application_date"])
    .dt.to_period("M")
    .astype(str)
)

monthly_monitoring = (
    df.groupby(
        ["application_month", "gender"]
    )
    .agg(
        Applications=("approved_flag", "size"),
        Approved=("approved_flag", "sum"),
        Approval_Rate=("approved_flag", "mean")
    )
    .reset_index()
)

monthly_monitoring["Approval_Rate"] = (
    monthly_monitoring["Approval_Rate"] * 100
).round(2)

display(monthly_monitoring)


# ================================================================
# 29. MONTHLY DISPARITY RANGE
# ================================================================

monthly_disparity = (
    monthly_monitoring
    .groupby("application_month")
    .agg(
        Highest_Approval_Rate=("Approval_Rate", "max"),
        Lowest_Approval_Rate=("Approval_Rate", "min")
    )
    .reset_index()
)

monthly_disparity["Disparity"] = (
    monthly_disparity["Highest_Approval_Rate"] -
    monthly_disparity["Lowest_Approval_Rate"]
).round(2)

monthly_disparity["Lowest_to_Highest_Ratio"] = (
    monthly_disparity["Lowest_Approval_Rate"] /
    monthly_disparity["Highest_Approval_Rate"]
).round(3)

display(monthly_disparity)


# ================================================================
# 30. FINAL FAIRNESS FLAGS
# ================================================================

print("\n" + "=" * 70)
print("26. FINAL FAIRNESS FLAGS")
print("=" * 70)

final_flags = fairness_summary.copy()

final_flags["Fairness_Flag"] = np.where(
    final_flags["Lowest_to_Highest_Ratio"] < 0.80,
    "Potential Disparity - Investigate",
    "No Automatic Flag"
)

display(final_flags)


# ================================================================
# 31. METHODOLOGY SUMMARY
# ================================================================

print("\n" + "=" * 70)
print("27. METHODOLOGY")
print("=" * 70)

methodology = {
    "Outcome":
        "Loan application decision (Approved/Rejected)",

    "Primary Metric":
        "Approval / Selection Rate",

    "Disparity Metric":
        "Difference between highest and lowest group approval rates",

    "Ratio Metric":
        "Lowest group approval rate divided by highest group approval rate",

    "Screening Threshold":
        "0.80 selection-rate ratio used as an investigation screening indicator",

    "Groups Analysed":
        "Gender, Region and Education",

    "Additional Factors":
        "Age, Annual Income, Credit Score and Application patterns",

    "Monitoring":
        "Monthly group-level approval rates and disparity ratio",

    "Limitation":
        "Descriptive analysis alone cannot establish causation or prove discrimination"
}

methodology_df = pd.DataFrame(
    list(methodology.items()),
    columns=["Methodology_Item", "Description"]
)

display(methodology_df)


# ================================================================
# 32. LIMITATIONS
# ================================================================

print("\n" + "=" * 70)
print("28. LIMITATIONS")
print("=" * 70)

limitations = [
    "The analysis identifies statistical disparities but does not establish causation.",
    "Small group sizes can make disparity estimates unstable.",
    "Observed differences may be influenced by legitimate business factors.",
    "The 80% rule is used as a screening indicator, not as a definitive legal conclusion.",
    "Historical data may contain existing bias that cannot be identified from outcome rates alone.",
    "Additional model-level analysis would be required if a predictive model is used.",
    "Fairness metrics should be monitored continuously rather than treated as a one-time audit."
]

for i, item in enumerate(limitations, 1):
    print(f"{i}. {item}")


# ================================================================
# 33. ACTION RECOMMENDATIONS
# ================================================================

print("\n" + "=" * 70)
print("29. RECOMMENDED ACTIONS")
print("=" * 70)

actions = [
    "Establish the current results as the fairness baseline.",
    "Investigate groups showing large approval-rate differences.",
    "Check whether legitimate business variables explain observed differences.",
    "Review small-group results carefully before drawing conclusions.",
    "Monitor approval rates and selection-rate ratios regularly.",
    "Document methodology, assumptions, limitations and decisions.",
    "Escalate persistent or material disparities for deeper investigation."
]

for i, action in enumerate(actions, 1):
    print(f"{i}. {action}")


# ================================================================
# 34. EXPORT ALL ANALYSIS RESULTS TO EXCEL
# ================================================================

print("\n" + "=" * 70)
print("30. EXPORTING ANALYSIS RESULTS")
print("=" * 70)

output_file = "/content/task14_fairness_analysis_results.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:

    df.to_excel(
        writer,
        sheet_name="Analysed_Data",
        index=False
    )

    missing_report.to_excel(
        writer,
        sheet_name="Data_Quality"
    )

    outcome_percentage.to_excel(
        writer,
        sheet_name="Outcome_Distribution"
    )

    gender_analysis.to_excel(
        writer,
        sheet_name="Gender_Analysis",
        index=False
    )

    region_analysis.to_excel(
        writer,
        sheet_name="Region_Analysis",
        index=False
    )

    education_analysis.to_excel(
        writer,
        sheet_name="Education_Analysis",
        index=False
    )

    gender_disparity.to_excel(
        writer,
        sheet_name="Gender_Disparity",
        index=False
    )

    region_disparity.to_excel(
        writer,
        sheet_name="Region_Disparity",
        index=False
    )

    education_disparity.to_excel(
        writer,
        sheet_name="Education_Disparity",
        index=False
    )

    gender_region.to_excel(
        writer,
        sheet_name="Gender_Region",
        index=False
    )

    gender_education.to_excel(
        writer,
        sheet_name="Gender_Education",
        index=False
    )

    credit_band_analysis.to_excel(
        writer,
        sheet_name="Credit_Band",
        index=False
    )

    income_band_analysis.to_excel(
        writer,
        sheet_name="Income_Band",
        index=False
    )

    age_analysis.to_excel(
        writer,
        sheet_name="Age_Band",
        index=False
    )

    consent_analysis.to_excel(
        writer,
        sheet_name="Consent_Analysis",
        index=False
    )

    fairness_summary.to_excel(
        writer,
        sheet_name="Fairness_Summary",
        index=False
    )

    review_df.to_excel(
        writer,
        sheet_name="Review_Actions",
        index=False
    )

    monthly_monitoring.to_excel(
        writer,
        sheet_name="Monthly_Monitoring",
        index=False
    )

    monthly_disparity.to_excel(
        writer,
        sheet_name="Monthly_Disparity",
        index=False
    )

    final_flags.to_excel(
        writer,
        sheet_name="Final_Flags",
        index=False
    )

    methodology_df.to_excel(
        writer,
        sheet_name="Methodology",
        index=False
    )


# ================================================================
# 35. EXPORT KEY TABLES AS CSV
# ================================================================

fairness_summary.to_csv(
    "/content/fairness_summary.csv",
    index=False
)

gender_disparity.to_csv(
    "/content/gender_disparity.csv",
    index=False
)

region_disparity.to_csv(
    "/content/region_disparity.csv",
    index=False
)

education_disparity.to_csv(
    "/content/education_disparity.csv",
    index=False
)

monthly_disparity.to_csv(
    "/content/monthly_fairness_monitoring.csv",
    index=False
)


# ================================================================
# 36. FINAL COMPLETION MESSAGE
# ================================================================

print("\n" + "=" * 70)
print("TASK 14 GOOGLE COLAB ANALYSIS COMPLETED")
print("=" * 70)

print("""
Completed:

1. Data quality validation
2. Outcome analysis
3. Group distribution analysis
4. Gender disparity analysis
5. Region disparity analysis
6. Education disparity analysis
7. Selection-rate ratio
8. 80% rule screening
9. Intersectional analysis
10. Income analysis
11. Credit-score analysis
12. Age-band analysis
13. Consent analysis
14. Sample-size assessment
15. Fairness baseline
16. Monthly monitoring
17. Methodology
18. Limitations
19. Recommended actions
20. Excel/CSV result export

Charts and dashboard have intentionally NOT been created.
They will be built later in Tableau.
""")

print("\nMain output file:")
print(output_file)

======================================================================
TASK 14 - FAIRNESS & BIAS ANALYSIS
======================================================================

Dataset loaded successfully.
Rows    : 500
Columns : 13

Columns:
['application_id', 'gender', 'age', 'region', 'education', 'experience_years', 'annual_income', 'credit_score', 'loan_amount', 'application_date', 'decision', 'processing_time_days', 'consent_for_fairness_audit']

======================================================================
1. BASIC DATA OVERVIEW
======================================================================

Dataset Shape:
(500, 13)

Data Types:
application_id                        object
gender                                object
age                                    int64
region                                object
education                             object
experience_years                       int64
annual_income                          int64
credit_score                           int64
loan_amount                            int64
application_date              datetime64[ns]
decision                              object
processing_time_days                 float64
consent_for_fairness_audit            object
dtype: object

First 5 Records:

,application_id,gender,age,region,education,experience_years,annual_income,credit_score,loan_amount,application_date,decision,processing_time_days,consent_for_fairness_audit
0,APP10001,Male,37,West,Master,12,88167,729,14379,2025-08-02,Approved,4.90,Yes
1,APP10002,Female,29,North,Master,8,109733,734,42485,2025-10-18,Approved,6.30,Yes
2,APP10003,Female,53,South,Bachelor,26,36097,621,19569,2025-01-22,Approved,6.00,Yes
3,APP10004,Female,40,North,Master,14,40903,698,23441,2025-07-12,Approved,3.70,Yes
4,APP10005,Male,33,South,Bachelor,13,61286,609,31977,2025-05-30,Rejected,2.90,No

Statistical Summary:

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
application_id,500,500,APP10500,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,500,3,Female,243,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,500.00,NaN,NaN,NaN,40.58,21.00,30.00,41.00,51.00,60.00,11.86
region,500,4,North,145,NaN,NaN,NaN,NaN,NaN,NaN,NaN
education,500,4,Bachelor,233,NaN,NaN,NaN,NaN,NaN,NaN,NaN
experience_years,500.00,NaN,NaN,NaN,16.12,0.00,5.00,16.50,26.00,39.00,11.63
annual_income,500.00,NaN,NaN,NaN,"66,210.59","18,000.00","51,026.50","66,535.00","81,952.00","136,602.00","22,201.42"
credit_score,500.00,NaN,NaN,NaN,695.94,471.00,651.75,698.00,744.25,850.00,75.99
loan_amount,500.00,NaN,NaN,NaN,"25,369.82","5,000.00","17,019.00","25,903.00","32,996.25","58,001.00","11,342.16"
application_date,500,NaN,NaN,NaN,2025-07-07 01:00:28.800000256,2025-01-03 00:00:00,2025-04-05 18:00:00,2025-07-12 12:00:00,2025-10-08 12:00:00,2025-12-31 00:00:00,NaN
decision,500,2,Approved,442,NaN,NaN,NaN,NaN,NaN,NaN,NaN
processing_time_days,500.00,NaN,NaN,NaN,3.47,1.00,2.60,3.50,4.30,7.10,1.21
consent_for_fairness_audit,500,2,Yes,462,NaN,NaN,NaN,NaN,NaN,NaN,NaN

======================================================================
2. DATA QUALITY VALIDATION
======================================================================

Missing Values:

                            Missing_Values  Missing_Percentage
application_id                           0                0.00
gender                                   0                0.00
age                                      0                0.00
region                                   0                0.00
education                                0                0.00
experience_years                         0                0.00
annual_income                            0                0.00
credit_score                             0                0.00
loan_amount                              0                0.00
application_date                         0                0.00
decision                                 0                0.00
processing_time_days                     0                0.00
consent_for_fairness_audit               0                0.00

Duplicate Records:
0

======================================================================
3. OUTCOME VARIABLE
======================================================================
Outcome Variable: decision

Outcome Distribution:

          Count
decision
Approved    442
Rejected     58

Outcome Percentage:

          Percentage
decision
Approved       88.40
Rejected       11.60

Approved = 1
Rejected = 0

Overall Approval Rate: 88.4 %

======================================================================
4. GROUP DISTRIBUTION
======================================================================

--- GENDER ---

            Count  Percentage
gender
Female        243       48.60
Male          233       46.60
Non-Binary     24        4.80

--- REGION ---

        Count  Percentage
region
North     145       29.00
South     130       26.00
East      121       24.20
West      104       20.80

--- EDUCATION ---

             Count  Percentage
education
Bachelor       233       46.60
Master         143       28.60
High School    100       20.00
PhD             24        4.80

======================================================================
5. OUTCOME DISPARITY - GENDER
======================================================================

       gender  Total_Applications  Approved  Approval_Rate  Rejection_Rate
0      Female                 243       209          86.01           13.99
1        Male                 233       212          90.99            9.01
2  Non-Binary                  24        21          87.50           12.50

======================================================================
6. OUTCOME DISPARITY - REGION
======================================================================

  region  Total_Applications  Approved  Approval_Rate  Rejection_Rate
0   East                 121       106          87.60           12.40
1  North                 145       126          86.90           13.10
2  South                 130       119          91.54            8.46
3   West                 104        91          87.50           12.50

======================================================================
7. OUTCOME DISPARITY - EDUCATION
======================================================================

     education  Total_Applications  Approved  Approval_Rate  Rejection_Rate
0     Bachelor                 233       206          88.41           11.59
1  High School                 100        88          88.00           12.00
2       Master                 143       125          87.41           12.59
3          PhD                  24        23          95.83            4.17

======================================================================
8. GENDER DISPARITY METRICS
======================================================================

,gender,Applications,Approved,Approval_Rate,Approval_Rate_Difference_From_Highest,Selection_Rate_Ratio
0,Female,243,209,86.01,4.98,0.94
1,Male,233,212,90.99,0.00,1.00
2,Non-Binary,24,21,87.50,3.49,0.96

======================================================================
9. REGION DISPARITY METRICS
======================================================================

,region,Applications,Approved,Approval_Rate,Approval_Rate_Difference_From_Highest,Selection_Rate_Ratio
0,East,121,106,87.60,3.94,0.96
1,North,145,126,86.90,4.64,0.95
2,South,130,119,91.54,0.00,1.00
3,West,104,91,87.50,4.04,0.96

======================================================================
10. EDUCATION DISPARITY METRICS
======================================================================

,education,Applications,Approved,Approval_Rate,Approval_Rate_Difference_From_Highest,Selection_Rate_Ratio
0,Bachelor,233,206,88.41,7.42,0.92
1,High School,100,88,88.00,7.83,0.92
2,Master,143,125,87.41,8.42,0.91
3,PhD,24,23,95.83,0.00,1.00

======================================================================
11. HIGHEST & LOWEST APPROVAL GROUPS
======================================================================

Group: gender
Highest Approval: Male -> 90.99 %
Lowest Approval: Female -> 86.01 %
Absolute Difference: 4.98 percentage points

Group: region
Highest Approval: South -> 91.54 %
Lowest Approval: North -> 86.9 %
Absolute Difference: 4.64 percentage points

Group: education
Highest Approval: PhD -> 95.83 %
Lowest Approval: Master -> 87.41 %
Absolute Difference: 8.42 percentage points

======================================================================
12. 80% RULE SCREENING
======================================================================

This is a screening indicator, not a final legal conclusion.

A selection-rate ratio below 0.80 can indicate a potential
disparity that requires further investigation.


 GENDER

,gender,Applications,Approved,Approval_Rate,Approval_Rate_Difference_From_Highest,Selection_Rate_Ratio,Potential_Disparity
0,Female,243,209,86.01,4.98,0.94,No Automatic Flag
1,Male,233,212,90.99,0.00,1.00,No Automatic Flag
2,Non-Binary,24,21,87.50,3.49,0.96,No Automatic Flag

 REGION

,region,Applications,Approved,Approval_Rate,Approval_Rate_Difference_From_Highest,Selection_Rate_Ratio,Potential_Disparity
0,East,121,106,87.60,3.94,0.96,No Automatic Flag
1,North,145,126,86.90,4.64,0.95,No Automatic Flag
2,South,130,119,91.54,0.00,1.00,No Automatic Flag
3,West,104,91,87.50,4.04,0.96,No Automatic Flag

 EDUCATION

,education,Applications,Approved,Approval_Rate,Approval_Rate_Difference_From_Highest,Selection_Rate_Ratio,Potential_Disparity
0,Bachelor,233,206,88.41,7.42,0.92,No Automatic Flag
1,High School,100,88,88.00,7.83,0.92,No Automatic Flag
2,Master,143,125,87.41,8.42,0.91,No Automatic Flag
3,PhD,24,23,95.83,0.00,1.00,No Automatic Flag

======================================================================
13. GENDER + REGION ANALYSIS
======================================================================

        gender region  Applications  Approved  Approval_Rate
0       Female   East            49        42          85.71
1       Female  North            74        60          81.08
2       Female  South            68        63          92.65
3       Female   West            52        44          84.62
4         Male   East            63        57          90.48
5         Male  North            65        61          93.85
6         Male  South            59        53          89.83
7         Male   West            46        41          89.13
8   Non-Binary   East             9         7          77.78
9   Non-Binary  North             6         5          83.33
10  Non-Binary  South             3         3         100.00
11  Non-Binary   West             6         6         100.00

======================================================================
14. GENDER + EDUCATION ANALYSIS
======================================================================

        gender    education  Applications  Approved  Approval_Rate
0       Female     Bachelor           120       103          85.83
1       Female  High School            47        42          89.36
2       Female       Master            68        56          82.35
3       Female          PhD             8         8         100.00
4         Male     Bachelor           103        94          91.26
5         Male  High School            49        42          85.71
6         Male       Master            68        64          94.12
7         Male          PhD            13        12          92.31
8   Non-Binary     Bachelor            10         9          90.00
9   Non-Binary  High School             4         4         100.00
10  Non-Binary       Master             7         5          71.43
11  Non-Binary          PhD             3         3         100.00

======================================================================
15. INCOME ANALYSIS BY GROUP
======================================================================

       gender  Average_Income  Median_Income
0      Female       66,062.35      66,535.00
1        Male       66,987.27      67,090.00
2  Non-Binary       60,171.21      55,792.50

======================================================================
16. CREDIT SCORE ANALYSIS BY GROUP
======================================================================

       gender  Average_Credit_Score  Median_Credit_Score
0      Female                698.27               698.00
1        Male                691.50               698.00
2  Non-Binary                715.33               718.00

======================================================================
17. CREDIT SCORE BAND ANALYSIS
======================================================================

  credit_score_band  Applications  Approved  Approval_Rate
0              Poor            37        23          62.16
1              Fair           130       103          79.23
2              Good           194       179          92.27
3         Very Good           139       137          98.56

======================================================================
18. INCOME BAND ANALYSIS
======================================================================

  income_band  Applications  Approved  Approval_Rate
0         Low            58        49          84.48
1      Medium           231       204          88.31
2        High           181       159          87.85
3   Very High            30        30         100.00

======================================================================
19. AGE BAND ANALYSIS
======================================================================

  age_band  Applications  Approved  Approval_Rate
0    18-25            71        58          81.69
1    26-35           122       104          85.25
2    36-45           106        89          83.96
3    46-55           137       130          94.89
4      56+            64        61          95.31

======================================================================
20. CONSENT ANALYSIS
======================================================================

  consent_for_fairness_audit  Applications  Approved  Approval_Rate
0                         No            38        29          76.32
1                        Yes           462       413          89.39

Consent Distribution:

                            Percentage
consent_for_fairness_audit
Yes                              92.40
No                                7.60

======================================================================
21. SAMPLE SIZE CHECK
======================================================================

 GENDER

            Sample_Size                    Small_Group_Flag
gender
Female              243   Adequate for Descriptive Analysis
Male                233   Adequate for Descriptive Analysis
Non-Binary           24  Small Sample - Interpret Carefully

 REGION

        Sample_Size                   Small_Group_Flag
region
North           145  Adequate for Descriptive Analysis
South           130  Adequate for Descriptive Analysis
East            121  Adequate for Descriptive Analysis
West            104  Adequate for Descriptive Analysis

 EDUCATION

             Sample_Size                    Small_Group_Flag
education
Bachelor             233   Adequate for Descriptive Analysis
Master               143   Adequate for Descriptive Analysis
High School          100   Adequate for Descriptive Analysis
PhD                   24  Small Sample - Interpret Carefully

======================================================================
22. OVERALL FAIRNESS SUMMARY
======================================================================

,Group_Type,Highest_Approval_Rate,Lowest_Approval_Rate,Absolute_Disparity,Lowest_to_Highest_Ratio
0,Gender,90.99,86.01,4.98,0.94
1,Region,91.54,86.90,4.64,0.95
2,Education,95.83,87.41,8.42,0.91

======================================================================
23. AREAS REQUIRING REVIEW
======================================================================

  Group_Type                       Issue               Action
0     Gender  No automatic 80% rule flag  Continue monitoring
1     Region  No automatic 80% rule flag  Continue monitoring
2  Education  No automatic 80% rule flag  Continue monitoring

======================================================================
24. FAIRNESS MONITORING BASELINE
======================================================================

,Group_Type,Highest_Approval_Rate,Lowest_Approval_Rate,Absolute_Disparity,Lowest_to_Highest_Ratio,Monitoring_Status
0,Gender,90.99,86.01,4.98,0.94,Baseline Established
1,Region,91.54,86.90,4.64,0.95,Baseline Established
2,Education,95.83,87.41,8.42,0.91,Baseline Established

======================================================================
25. MONTHLY FAIRNESS MONITORING
======================================================================

   application_month      gender  Applications  Approved  Approval_Rate
0            2025-01      Female            20        18          90.00
1            2025-01        Male            22        20          90.91
2            2025-01  Non-Binary             1         1         100.00
3            2025-02      Female            18        16          88.89
4            2025-02        Male            11        10          90.91
5            2025-02  Non-Binary             4         4         100.00
6            2025-03      Female            18        12          66.67
7            2025-03        Male            22        20          90.91
8            2025-03  Non-Binary             3         2          66.67
9            2025-04      Female            24        21          87.50
10           2025-04        Male            17        16          94.12
11           2025-04  Non-Binary             1         1         100.00
12           2025-05      Female            17        15          88.24
13           2025-05        Male            22        21          95.45
14           2025-05  Non-Binary             2         2         100.00
15           2025-06      Female            17        16          94.12
16           2025-06        Male            16        15          93.75
17           2025-06  Non-Binary             1         1         100.00
18           2025-07      Female            23        18          78.26
19           2025-07        Male            21        19          90.48
20           2025-07  Non-Binary             3         2          66.67
21           2025-08      Female            17        15          88.24
22           2025-08        Male            20        18          90.00
23           2025-09      Female            16        14          87.50
24           2025-09        Male            21        19          90.48
25           2025-09  Non-Binary             2         2         100.00
26           2025-10      Female            25        21          84.00
27           2025-10        Male            24        21          87.50
28           2025-10  Non-Binary             3         3         100.00
29           2025-11      Female            25        24          96.00
30           2025-11        Male            16        14          87.50
31           2025-11  Non-Binary             2         1          50.00
32           2025-12      Female            23        19          82.61
33           2025-12        Male            21        19          90.48
34           2025-12  Non-Binary             2         2         100.00

,application_month,Highest_Approval_Rate,Lowest_Approval_Rate,Disparity,Lowest_to_Highest_Ratio
0,2025-01,100.00,90.00,10.00,0.90
1,2025-02,100.00,88.89,11.11,0.89
2,2025-03,90.91,66.67,24.24,0.73
3,2025-04,100.00,87.50,12.50,0.88
4,2025-05,100.00,88.24,11.76,0.88
5,2025-06,100.00,93.75,6.25,0.94
6,2025-07,90.48,66.67,23.81,0.74
7,2025-08,90.00,88.24,1.76,0.98
8,2025-09,100.00,87.50,12.50,0.88
9,2025-10,100.00,84.00,16.00,0.84
10,2025-11,96.00,50.00,46.00,0.52
11,2025-12,100.00,82.61,17.39,0.83

======================================================================
26. FINAL FAIRNESS FLAGS
======================================================================

,Group_Type,Highest_Approval_Rate,Lowest_Approval_Rate,Absolute_Disparity,Lowest_to_Highest_Ratio,Fairness_Flag
0,Gender,90.99,86.01,4.98,0.94,No Automatic Flag
1,Region,91.54,86.90,4.64,0.95,No Automatic Flag
2,Education,95.83,87.41,8.42,0.91,No Automatic Flag

======================================================================
27. METHODOLOGY
======================================================================

      Methodology_Item                                        Description
0              Outcome      Loan application decision (Approved/Rejected)
1       Primary Metric                          Approval / Selection Rate
2     Disparity Metric  Difference between highest and lowest group ap...
3         Ratio Metric  Lowest group approval rate divided by highest ...
4  Screening Threshold  0.80 selection-rate ratio used as an investiga...
5      Groups Analysed                       Gender, Region and Education
6   Additional Factors  Age, Annual Income, Credit Score and Applicati...
7           Monitoring  Monthly group-level approval rates and dispari...
8           Limitation  Descriptive analysis alone cannot establish ca...

======================================================================
28. LIMITATIONS
======================================================================
1. The analysis identifies statistical disparities but does not establish causation.
2. Small group sizes can make disparity estimates unstable.
3. Observed differences may be influenced by legitimate business factors.
4. The 80% rule is used as a screening indicator, not as a definitive legal conclusion.
5. Historical data may contain existing bias that cannot be identified from outcome rates alone.
6. Additional model-level analysis would be required if a predictive model is used.
7. Fairness metrics should be monitored continuously rather than treated as a one-time audit.

======================================================================
29. RECOMMENDED ACTIONS
======================================================================
1. Establish the current results as the fairness baseline.
2. Investigate groups showing large approval-rate differences.
3. Check whether legitimate business variables explain observed differences.
4. Review small-group results carefully before drawing conclusions.
5. Monitor approval rates and selection-rate ratios regularly.
6. Document methodology, assumptions, limitations and decisions.
7. Escalate persistent or material disparities for deeper investigation.

======================================================================
30. EXPORTING ANALYSIS RESULTS
======================================================================

======================================================================
TASK 14 GOOGLE COLAB ANALYSIS COMPLETED
======================================================================

Completed:

1. Data quality validation
2. Outcome analysis
3. Group distribution analysis
4. Gender disparity analysis
5. Region disparity analysis
6. Education disparity analysis
7. Selection-rate ratio
8. 80% rule screening
9. Intersectional analysis
10. Income analysis
11. Credit-score analysis
12. Age-band analysis
13. Consent analysis
14. Sample-size assessment
15. Fairness baseline
16. Monthly monitoring
17. Methodology
18. Limitations
19. Recommended actions
20. Excel/CSV result export

Charts and dashboard have intentionally NOT been created.
They will be built later in Tableau.


Main output file:
/content/task14_fairness_analysis_results.xlsx